apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: my-app
      env: dev
  template:
    metadata:
      name: my-pod
      labels:
        app: my-app
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name:  my-svc
spec:
  selector:
    app:  my-app
  type:   NodePort
  ports:
  - name:  http
    port:  80
    targetPort:  80
